<?php

header("Content-Type: application/json");

require_once "../connection.php";
require_once "../config/jwt.php";

use Firebase\JWT\JWT;
use Firebase\JWT\Key;

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode([
        "status" => false,
        "message" => "Only POST method is allowed"
    ]);
    exit;
}

$headers = getallheaders();
$authHeader = $headers['Authorization'] ?? '';

if ($authHeader === '') {
    echo json_encode([
        "status" => false,
        "message" => "Authorization token is required"
    ]);
    exit;
}

if (!preg_match('/Bearer\s(\S+)/', $authHeader, $matches)) {
    echo json_encode([
        "status" => false,
        "message" => "Invalid authorization format"
    ]);
    exit;
}

$accessToken = $matches[1];

try {

    $decoded = JWT::decode(
        $accessToken,
        new Key($secret_key, "HS256")
    );

} catch (Throwable $e) {

    echo json_encode([
        "status" => false,
        "message" => "Invalid or expired access token"
    ]);
    exit;
}

$userId = $decoded->user_id ?? null;
$role = $decoded->role ?? null;

if (!$userId || $role !== "user") {
    echo json_encode([
        "status" => false,
        "message" => "Only users can make payments"
    ]);
    exit;
}

$data = json_decode(
    file_get_contents("php://input"),
    true
);

$bookingId = (int)($data['booking_id'] ?? 0);
$paymentMethod = trim($data['payment_method'] ?? '');
$transactionId = trim($data['transaction_id'] ?? '');

if ($bookingId <= 0) {
    echo json_encode([
        "status" => false,
        "message" => "Valid booking ID is required"
    ]);
    exit;
}

if ($paymentMethod === '') {
    echo json_encode([
        "status" => false,
        "message" => "Payment method is required"
    ]);
    exit;
}

/*
 * Transaction ID can be generated by the
 * payment gateway. For testing, if it is
 * not supplied, generate one.
 */
if ($transactionId === '') {

    $transactionId = "SPORTO_" .
        strtoupper(bin2hex(random_bytes(6)));
}

$con->begin_transaction();

try {

    /*
     * Get booking and lock it.
     */
    $bookingStmt = $con->prepare(
        "SELECT
            b.id,
            b.user_id,
            b.turf_id,
            b.slot_id,
            b.amount,
            b.status,
            s.status AS slot_status
         FROM bookings b
         INNER JOIN turf_slots s
            ON b.slot_id = s.id
         WHERE b.id = ?
         AND b.user_id = ?
         LIMIT 1
         FOR UPDATE"
    );

    $bookingStmt->bind_param(
        "ii",
        $bookingId,
        $userId
    );

    $bookingStmt->execute();

    $bookingResult = $bookingStmt->get_result();

    if ($bookingResult->num_rows === 0) {

        throw new Exception(
            "Booking not found"
        );
    }

    $booking = $bookingResult->fetch_assoc();

    /*
     * Validate booking status.
     */
    if ($booking['status'] === 'cancelled') {

        throw new Exception(
            "Cancelled booking cannot be paid"
        );
    }

    if ($booking['status'] === 'completed') {

        throw new Exception(
            "Booking is already completed"
        );
    }

    if ($booking['status'] === 'confirmed') {

        throw new Exception(
            "Booking is already paid"
        );
    }

    /*
     * Check existing successful payment.
     */
    $paymentCheck = $con->prepare(
        "SELECT id
         FROM payments
         WHERE booking_id = ?
         AND status = 'success'
         LIMIT 1"
    );

    $paymentCheck->bind_param(
        "i",
        $bookingId
    );

    $paymentCheck->execute();

    $paymentResult = $paymentCheck->get_result();

    if ($paymentResult->num_rows > 0) {

        throw new Exception(
            "Payment has already been completed"
        );
    }

    $paymentCheck->close();

    /*
     * Make sure slot is still booked.
     */
    if ($booking['slot_status'] !== 'booked') {

        throw new Exception(
            "This turf slot is no longer reserved"
        );
    }

    $amount = (float)$booking['amount'];
    $paymentStatus = "success";
    $paymentDate = date("Y-m-d H:i:s");

    /*
     * Create payment record.
     */
    $paymentStmt = $con->prepare(
        "INSERT INTO payments
        (
            booking_id,
            amount,
            payment_method,
            transaction_id,
            status,
            payment_date
        )
        VALUES (?, ?, ?, ?, ?, ?)"
    );

    $paymentStmt->bind_param(
        "idssss",
        $bookingId,
        $amount,
        $paymentMethod,
        $transactionId,
        $paymentStatus,
        $paymentDate
    );

    if (!$paymentStmt->execute()) {

        throw new Exception(
            "Failed to create payment record"
        );
    }

    $paymentId = $paymentStmt->insert_id;

    /*
     * Confirm booking.
     */
    $bookingUpdate = $con->prepare(
        "UPDATE bookings
         SET status = 'confirmed'
         WHERE id = ?
         AND user_id = ?"
    );

    $bookingUpdate->bind_param(
        "ii",
        $bookingId,
        $userId
    );

    if (!$bookingUpdate->execute()) {

        throw new Exception(
            "Failed to confirm booking"
        );
    }

    /*
     * Keep slot booked.
     */
    $slotUpdate = $con->prepare(
        "UPDATE turf_slots
         SET status = 'booked'
         WHERE id = ?"
    );

    $slotUpdate->bind_param(
        "i",
        $booking['slot_id']
    );

    if (!$slotUpdate->execute()) {

        throw new Exception(
            "Failed to update turf slot"
        );
    }

    $slotUpdate->close();
    $bookingUpdate->close();
    $paymentStmt->close();
    $bookingStmt->close();

    $con->commit();

    echo json_encode([
        "status" => true,
        "message" => "Payment successful",
        "payment" => [
            "id" => $paymentId,
            "booking_id" => $bookingId,
            "amount" => $amount,
            "payment_method" => $paymentMethod,
            "transaction_id" => $transactionId,
            "status" => $paymentStatus,
            "payment_date" => $paymentDate
        ],
        "booking" => [
            "id" => $bookingId,
            "status" => "confirmed"
        ]
    ]);

} catch (Throwable $e) {

    $con->rollback();

    echo json_encode([
        "status" => false,
        "message" => $e->getMessage()
    ]);
}

$con->close();

?>